sudo: false
language: java
env:
  global:
    - # GITHUB_TOKEN
    - secure: "rDHKM2gc9GWl96ocfNk0dmoIEOMBZDg+SBgy6XamYSxxKILXiI9FxcLFgLcQmNwQxsCwCe7aJBFeeMKcc/b8wzrOER77PvOFnZ7AcLGS7YjBLP++mWYvqc6eJ91tVZxVBvFJ04UidEDAGaeanc7j4OmqkPQkik2x9AHztOkVkahaBqVopvtsJlcXwyL08DMqS83zpEaBqbGfJx9FjZoUKYU1VRhjtLgI6HbX7DlXw+95ny7T1LLWtDWzKbqhf1ZCWdFwdJuRNu85jEKw3tmwJzIkmna0+pj6Qx5211tdQQbfC7g7YplsVq7VSSIxrJWaaMT0FyhNnA8dHlcLCuglGf2OmHCIceLtbpRWdfVULoce9qoZqmftjn0bHF00qnFE0k7Yz+5m1UgYZKaMCihB0Td1avsFvIK92vj0f1Z7AYqNKKfuS4woip33BZ+6Zqd8HiCaDo6kFLdRWtqLVX2A+nxT7Y3LxzgAsNUwFKBIIljBAL5foCPqtMbpnJg1Q/Ns9eqdHd+VATvPoeckTTeAbB0RoMGNzqQJAhsbjEkcSh58fUxTnfqpGqRS8Qnp+r6jV/CQV0v7lHCUrTNmxfzdwahfdiaqidV7KOv9C/sFu05IWGB++Cu6XzSNIhwlqh2ZD6c0paKhpmIaaQDhuL4pBorKGkB1x2yZxizif6p0fBA="
    - # GRADLE_PUBLISH_KEY
    - secure: "B2SL8qfuXutwCFnur+iMbsK7jOeB8khUCpMAJL/bfclhZgtbxAwo2KdWMwAlPB6eiADKv00/xpMEEj2R94/RV/l0MlUMQBUk0Omh5ZuLgi+iuORExxKDpqriXk3h7PurFH3AFyc6JCHikB+JsJVK6XZROv1yde2UEvhhHtTGyNoZxGqGMhMcyHAF3ATEzr/lKnXAma3e9ddIaAfH+ATspaJMJm05zMjI9NYdgFb2lQSUWLhO0+fQUZ0XPfppcCX3putRsyOhdVE3kaWNLzBDqNJGYzlF1sj9bB9QPUTB55hX/RfCJylUjSpPa2KOV8ex0kXSiJKj4RZ4q7MI3hBTujofN/f5pqUKToINZHAPGZi+5M7Zdp5jpyqMh6dUYniKzJXPOSTWPhDACGvnUynZ9IpMTmxi+u8Of4Sb0K6qp7fvEuPk7hkNesy5w9AT1GMsaTFrn+QkeS6lC8Y5TZJIew/NibUwYO3XB8r7fQrp4xU+q+Tdj71DfO9JR86V9nLPMwSsDhhflXuncDkWgh+fvUsYask6hssQtnUUA8PebnbTmVWzuXJDhGvbUGTFyl2BF1YYrz5qGHsCpLm9D/8XHsNpb9FikKBcu4xsAC+MN1h0bE87zhItfe3l5IGZBJmSLFgaMcVfUt3phvYsLHJ4GQXeFLuR06Dxc6GkTyzz1IE="
    - # GRADLE_PUBLISH_SECRET
    - secure: "pUPf0RuqtYlAuZ4/ghNHC+TPgnozRj+kzD9HJ1j+JlduGa0ZNoLORsuNCSXwdDMdTeSCcgAeL/xV1O8MmGheh0irdgbtC/UvMtdzw+6hDBLeVDxWN1xhBV26ke7LbMnE2SKG1dc8oSedt2X+371uln7lPx7Rej6oUdTdEdi1QMdQzHZ5ft3fZeIAXl/8YjpJa8q9wzvdilzSHULE1pcCmK60MijAYXpEjDgV+K9/aYiUrcpTsfXtmr0r81iG85UkL6Be5VjKWqNy+gzdQPw4yCS/L7eagg6riCt3u4P7MFjkDgVKtvG9je/J8EKc+M5QdaFrnU0i3mYAHpDexjJMEuRJOvvT4QJHBNidKT/e3Vhhyq9x1n8amdAGnknKoTbT4pwOAou7VaqX4mjbGPWFheooYGbeuYWu7adaiE4HqHYteWKwwwCQ8yOWuL8GJQFrRww6VHsR6QNGW/VZlsRIlbhLDTeSaQcaVzBBRSO2m817rGYeFryQNFibXG212rO5IukFFy7HtIHf35avHTB/ZiAFVZuE6uFEs75xEXY36SmFPHzBINdSqQrkdAXZiKja3i1iCoQcHBV5sLiS93oKwCYHotn5BbIwM0BnEtSrDLPev67uzalmJ8siePXDjZfGHbdoA5YTJ78ByFZKZ2ujdxa3WlEFXKw74pXGvjYtT4g="

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: echo "skip install"

script: |-
  [ "${TRAVIS_PULL_REQUEST}" = "false" ] && source ci/setup-git.sh && ./gradlew release -Dorg.ajoberstar.grgit.auth.username=${GITHUB_TOKEN} -Dorg.ajoberstar.grgit.auth.password -Dgradle.publish.key=${GRADLE_PUBLISH_KEY} -Dgradle.publish.secret=${GRADLE_PUBLISH_SECRET} --info --stacktrace

notifications:
  email:
    on_success: never
    on_failure: never
